# GitHub Sponsors funding file
# This file is used to display sponsor information on the repository

# GitHub Sponsors
github: # Add your GitHub username here if you set up GitHub Sponsors

# Other funding platforms
patreon: # Add your Patreon username
open_collective: # Add your Open Collective username
ko_fi: # Add your Ko-fi username
tidelift: # Add your Tidelift package name
community_bridge: # Add your Community Bridge project name
liberapay: # Add your Liberapay username
issuehunt: # Add your IssueHunt username
otechie: # Add your Otechie username
lfx_crowdfunding: # Add your LFX Crowdfunding project name

# Custom funding URLs
custom: # Add up to 4 custom funding URLs
  # - https://www.buymeacoffee.com/yourusername
  # - https://www.paypal.me/yourusername